apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayurmart-coupon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ayurmart-coupon
  template:
    metadata:
      labels:
        app: ayurmart-coupon
    spec:
      containers:
        - name: ayurmart-coupon
          image: ayurmart-coupon:latest
          ports:
            - containerPort: 7003
---
apiVersion: v1
kind: Service
metadata:
  name: ayurmart-coupon
spec:
  selector:
    app: ayurmart-coupon
  ports:
    - name: http
      port: 80
      targetPort: 7003
